version: "3.8"

services:
  mysqldb:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: youssef
      MYSQL_DATABASE: TeamQuest
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  backend:
    depends_on:
      - mysqldb
    build:
      context: .
    restart: on-failure
    ports:
      - "8086:8086"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/TeamQuest?useSSL=false",
          "spring.datasource.username": "root",
          "spring.datasource.password": "youssef",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true
    networks:
      - app-network

  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
