version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=SOPRA
      - MYSQL_ROOT_PASSWORD=youssef
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/SOPRA?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: youssef
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SERVER_PORT: 8086
    networks:
      - backend
    stdin_open: true
    tty: true
 frontend:
    depends_on:
     - app
    build:
      context: ./Desktop/TeamQuestAng-main/TeamQuestAng-main
      dockerfile: Dockerfile
    image: teamquest-frontend
    ports:
      - "4200:80"
    networks:
      - backend
    depends_on:
      - app
volumes:
  db:

networks:
  backend:
    driver: bridge
