version: "3.8"

services:
  mysqldb:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: youssef
      MYSQL_DATABASE: TeamQuest
    ports:
      - "3307:3306"   # Map to 3307 on host to avoid conflict with XAMPP MySQL on 3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network

  backend:
    depends_on:
      - mysqldb
    build:
      context: .
    restart: on-failure
    ports:
      - "8086:8086"
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/TeamQuest?useSSL=false",
          "spring.datasource.username": "root",
          "spring.datasource.password": "youssef",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true
    networks:
      - app-network

  frontend:
    image: teamquest-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"   # Angular frontend on port 4200 - no conflict with XAMPP Apache on 8081
    networks:
      - app-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8083:8080"   # Adminer UI on 8083 - should be free
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
